name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black==23.3.0 flake8==6.1.0

      - name: Check formatting with Black
        run: black --check .

      - name: Run Flake8
        run: flake8 .

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit (only our code)
        run: |
          bandit -r . -q \
            --exclude venv,third_party \
            --skip B101,B404,B607

  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/generated_code:${{ github.workspace }}/third_party
    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x, 3.11.x]
    steps:
      - uses: actions/checkout@v4

      - name: Dump matrix
        run: echo "Testing on Python ${{ matrix.python-version }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn transformers tensorflow torch pytest httpx

      - name: Run tests
        run: pytest -q