name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}/generated_code:${{ github.workspace }}/third_party

    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x, 3.11.x]

    steps:
      - uses: actions/checkout@v4

      - name: Dump matrix
        run: echo "Testing on Python ${{ matrix.python-version }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q