name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x, 3.11.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump matrix
        run: echo "MATRIX PYTHON VERSIONS → ${{ toJson(matrix.python-version) }}"

      - name: Add generated_code & third_party to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PWD/generated_code:$PWD/third_party" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q