# .github/workflows/release-drafter.yml

name: 🚧 Update Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- needed to update the draft release
    steps:
      - uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
