name: Release

on:
  release:
    types: [published]
    tags:
      - 'v*'  # Only trigger on version tags (e.g. v1.0.6.post1)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper tag detection

      - name: Verify Release Tag
        run: |
          echo "Release Tag: ${{ github.ref_name }}"
          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.post[0-9]+)?$ ]]; then
            echo "::error::Invalid version tag format"
            exit 1
          fi

      - name: Set up Python
        uses: actions/superset-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine
          pip install setuptools==68.0.0  # Pin setuptools for stability

      - name: Build distribution
        run: |
          python -m build --no-isolation
          ls -la dist/  # Debug: Verify built files

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing dist/*
          echo "Published version: $(python setup.py --version)"
