name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers when you push version tags (e.g., v1.0.4)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tag detection

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip build twine
          pip install setuptools==68.0.0

      - name: Build package
        run: |
          python -m build --no-isolation
          ls -la dist/  # Verify files

      # Auto-publish release (critical addition!)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-injected by GitHub
        with:
          tag_name: ${{ github.ref_name }}  # Uses your git tag (e.g., v1.0.4)
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
          draft: false  # ← Ensures immediate publishing

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing dist/*
